// fsolauncher
// \src\store\actions\types.ts

export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const UPDATE_SHOW_WELCOME_SCREEN = "UPDATE_SHOW_WELCOME_SCREEN";
export const UPDATE_HEADER = "UPDATE_HEADER";
export const COMPOSE_MODAL = "COMPOSE_MODAL";
export const DISPOSE_MODAL = "DISPOSE_MODAL";
export const UPDATE_GLOBAL_PROGRESS = "UPDATE_GLOBAL_PROGRESS";
export const UPDATE_SOFTWARE = "UPDATE_SOFTWARE";
export const TOGGLE_RUNNING_TASK = "TOGGLE_RUNNING_TASK";
export const UPDATE_INTERNET_STATUS = "UPDATE_INTERNET_STATUS";
export const UPDATE_POSTS = "UPDATE_POSTS";
export const ADD_DOWNLOAD = "ADD_DOWNLOAD";
export const UPDATE_DOWNLOAD = "UPDATE_DOWNLOAD";
export const COMPOSE_TOAST = "COMPOSE_TOAST";
export const DISPOSE_TOAST = "DISPOSE_TOAST";
